[general]
import = [
   "~/.config/alacritty/themes/themes/night_owlish_light.toml"
]

[font]
normal.family = "JetBrainsMono Nerd Font"
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
# italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
# bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 15
